(feat) edit css styling and update playbooks info
kater-ai/kater-docs pull request #54
Opened 2024-10-08 05:20 UTC by yvonne-chou-1

2024-10-08 05:30 UTC, rob2244 requested changes

2024-10-08 05:30 UTC, rob2244 commented on docusaurus.config.ts
> +    // },
Delete unused code

2024-10-08 05:30 UTC, rob2244 commented on src/css/custom.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
Probably better to download this font and serve it as a static asset?

2024-10-08 23:54 UTC, yvonne-chou-1 commented on src/css/custom.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
I think it's fine to have it imported directly because the docs are public and we aren't worried about any privacy issues. Speed is also fine. The convenience of importing it exceeds serving it as a static asset.

2024-10-09 00:17 UTC, rob2244 approved these changes

2024-10-09 00:17 UTC, merged